name: Boardbyte CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Boardbyte Test
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npx prisma generate
      - run: npm run build --if-present
      - run: npm test
