name: Boardbyte CI

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Boardbyte Test
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: yarn install
      - run: npx prisma generate
      - run: yarn build
      - run: yarn test
